const API_BASE = window.CDSS_API_URL || 'http://127.0.0.1:8000';
const resourceConfig = {
  conditions: { label: 'Conditions', singular: 'condition', fields: ['name', 'description', 'severity', 'urgency'] },
  symptoms: { label: 'Symptoms', singular: 'symptom', fields: ['name', 'description'] },
  'risk-factors': { label: 'Risk Factors', singular: 'risk factor', fields: ['name', 'description', 'factor_type'] },
  tests: { label: 'Tests', singular: 'test', fields: ['name', 'description', 'purpose'] },
  treatments: { label: 'Treatments', singular: 'treatment', fields: ['name', 'description', 'treatment_type'] },
};
const state = { page: 'home', data: {}, selectedSymptoms: [], selectedRisks: [], results: null, expanded: 0, loading: false, error: '' };
const app = document.querySelector('#app');

async function api(path, options = {}) {
  const response = await fetch(`${API_BASE}${path}`, { headers: { 'Content-Type': 'application/json' }, ...options });
  if (!response.ok) {
    let message = 'The clinical decision support service could not complete that request.';
    try { const body = await response.json(); message = body.detail || message; } catch (_) { /* use safe fallback */ }
    throw new Error(message);
  }
  return response.json();
}
function escapeHtml(value = '') { return String(value).replace(/[&<>'"]/g, char => ({ '&': '&amp;', '<': '&lt;', '>': '&gt;', "'": '&#39;', '"': '&quot;' }[char])); }
function go(page) { state.page = page; state.error = ''; render(); if (page === 'evaluate') loadOptions(); if (page === 'knowledge' || page.startsWith('knowledge:')) loadResource(page.split(':')[1] || 'conditions'); }
function render() { app.innerHTML = state.page === 'home' ? landing() : application(); bindEvents(); }
function landing() {
  return `<header class="app-header"><a class="brand" href="#"><span class="brand-mark"></span>clarity<span style="color:var(--green-deep)">.</span></a><nav class="top-nav"><a href="#works">How it works</a><a href="#knowledge" data-page="knowledge">Knowledge Base</a><a href="#about">About</a></nav><div class="header-actions"><a href="#login">Login</a><button class="pill" data-page="evaluate">Start Evaluation</button></div></header>
  <main class="landing"><section class="hero"><div><span class="eyebrow">Clinical decision support</span><h1>Make clinical decisions with greater clarity.</h1><p class="hero-copy">Analyze patient symptoms and risk factors to identify possible conditions, prioritize urgency, and explore relevant diagnostic tests and treatments.</p><div class="hero-actions"><button class="pill" data-page="evaluate">Start Evaluation</button><button class="pill light" data-page="knowledge">Explore Knowledge Base</button></div><div class="trust"><i></i> Evidence-informed clinical decision support</div></div>${heroMockup()}</section></main>`;
}
function heroMockup() { return `<div class="mockup"><div class="mockup-top"><div><span class="kicker">Live assessment</span><h3>Patient evaluation</h3></div><span class="status">Ready to review</span></div><div class="mock-label">Symptoms</div><div class="tags"><span class="tag">Fever</span><span class="tag">Cough</span><span class="tag">Fatigue</span></div><div class="mock-label">Possible conditions</div><div class="mock-results"><div class="result-row"><div>Pneumonia<div class="bar"><b style="width:82%"></b></div></div><span class="score">82%</span></div><div class="result-row"><div>Influenza<div class="bar"><b style="width:64%"></b></div></div><span class="score">64%</span></div><div class="result-row"><div>Bronchitis<div class="bar"><b style="width:51%"></b></div></div><span class="score">51%</span></div></div><div class="mock-footer"><div class="mini-stat">Severity<strong>High</strong></div><div class="mini-stat">Urgency<strong>Moderate</strong></div><div class="mini-stat">Tests<strong>2 found</strong></div></div></div>`; }
function application() {
  const mobile = `<button class="mobile-menu" id="menu-button" aria-label="Open navigation">☰</button>`;
  return `<div class="app-shell"><aside class="sidebar" id="sidebar"><a class="brand" href="#" data-page="home"><span class="brand-mark"></span>clarity<span style="color:var(--green-deep)">.</span></a><div class="side-label">Workspace</div><nav class="side-nav">${navButton('overview', 'Overview')}${navButton('evaluate', 'Patient Evaluation')}${navButton('results', 'Results')}${navButton('knowledge', 'Knowledge Base')}</nav><div class="side-label" style="margin-top:27px">Knowledge</div><nav class="side-nav">${Object.entries(resourceConfig).map(([key, config]) => navButton(`knowledge:${key}`, config.label)).join('')}</nav><div class="sidebar-bottom"><nav class="side-nav"><button>Settings</button><button>About</button></nav></div></aside><main class="main">${mobile}${pageContent()}</main></div>`;
}
function navButton(page, label) { const active = state.page === page || (state.page === 'knowledge' && page.startsWith('knowledge')); return `<button class="${active ? 'active' : ''}" data-page="${page}">${label}</button>`; }
function pageContent() {
  if (state.page === 'evaluate') return evaluationPage();
  if (state.page === 'results') return resultsPage();
  if (state.page.startsWith('knowledge')) return knowledgePage(state.page.split(':')[1] || 'conditions');
  return overviewPage();
}
function pageHead(kicker, title, text, action = '') { return `<div class="page-head"><div><span class="kicker">${kicker}</span><h1>${title}</h1><p>${text}</p></div>${action}</div>`; }
function overviewPage() { return `${pageHead('Workspace', 'Good morning.', 'A clear view of your decision-support workspace and knowledge base.', '<button class="pill" data-page="evaluate">New evaluation</button>')}<div class="content-grid"><section class="panel"><div class="section-head"><div><h2>Start with a patient</h2><p>Use stored symptoms and risk factors to create a transparent assessment.</p></div></div><div class="notice">Results are software ranking signals based on relationships and weights stored in the knowledge base. They are not medically validated probabilities.</div><div class="form-actions"><button class="pill" data-page="evaluate">Open evaluation</button></div></section><aside class="panel"><h2>Knowledge base</h2><p>Available clinical resources</p><div class="info-list" style="margin-top:22px">${Object.entries(resourceConfig).map(([key, config]) => `<div class="info-item"><span>${config.label}</span><strong data-count="${key}">--</strong></div>`).join('')}</div></aside></div>`; }
function optionData(type) { return state.data[type] || []; }
async function loadOptions() { for (const type of ['symptoms', 'risk-factors']) { if (!state.data[type]) { try { state.data[type] = await api(`/${type}`); render(); } catch (error) { state.error = error.message; render(); } } } }
function evaluationPage() { const symptoms = optionData('symptoms'); const risks = optionData('risk-factors'); return `${pageHead('Evaluation', 'Patient evaluation', 'Enter symptoms and relevant risk factors to generate a clinical decision-support assessment.')} ${state.error ? `<div class="error">${escapeHtml(state.error)}</div>` : ''}<div class="content-grid"><section class="panel"><form id="evaluation-form"><div class="form-section"><h3>Patient information</h3><p>Optional context that will be forwarded to the evaluation service.</p><div class="field-grid"><label>Age<input name="age" type="number" min="0" max="130" placeholder="e.g. 54"></label><label>Sex<select name="sex"><option value="">Not specified</option><option>Female</option><option>Male</option><option>Intersex</option><option>Prefer not to say</option></select></label></div></div><div class="form-section"><h3>Symptoms</h3><p>Select the symptoms observed in this patient.</p>${selector('symptoms', state.selectedSymptoms, symptoms, 'Search symptoms...')}</div><div class="form-section"><h3>Risk factors</h3><p>Add relevant factors from the knowledge base.</p>${selector('risk-factors', state.selectedRisks, risks, 'Search risk factors...')}</div><div class="form-actions"><button class="pill" id="evaluate-button" type="submit">${state.loading ? 'Evaluating...' : 'Evaluate patient'}</button></div></form></section><aside class="panel"><h2>Before you begin</h2><p>Keep the assessment grounded in the available knowledge base.</p><div class="notice" style="margin-top:20px">The system provides decision-support information and is not a substitute for professional clinical judgment.</div><div class="info-list" style="margin-top:23px"><div class="info-item"><span>Symptoms loaded</span><strong>${symptoms.length}</strong></div><div class="info-item"><span>Risk factors loaded</span><strong>${risks.length}</strong></div></div></aside></div>`; }
function selector(type, selected, values, placeholder) { const query = state[`${type === 'symptoms' ? 'symptoms' : 'risks'}Query`] || ''; const filtered = values.filter(item => item.name.toLowerCase().includes(query.toLowerCase()) && !selected.includes(item.name)).slice(0, 8); return `<div class="choice-box">${selected.map(item => `<span class="choice">${escapeHtml(item)}<button type="button" data-remove="${type}" data-value="${escapeHtml(item)}">x</button></span>`).join('')}<input data-search="${type}" value="${escapeHtml(query)}" placeholder="${placeholder}"></div><div class="suggestions">${filtered.map(item => `<button type="button" class="suggestion" data-add="${type}" data-value="${escapeHtml(item.name)}">+ ${escapeHtml(item.name)}</button>`).join('')}</div>`; }
async function submitEvaluation(form) { const formData = new FormData(form); if (!state.selectedSymptoms.length) { state.error = 'Select at least one symptom to evaluate the patient.'; render(); return; } state.loading = true; state.error = ''; render(); const demographics = {}; if (formData.get('age')) demographics.age = Number(formData.get('age')); if (formData.get('sex')) demographics.sex = formData.get('sex'); try { state.results = await api('/evaluate', { method: 'POST', body: JSON.stringify({ symptoms: state.selectedSymptoms, risk_factors: state.selectedRisks, demographics }) }); state.page = 'results'; } catch (error) { state.error = error.message; } finally { state.loading = false; render(); } }
function resultsPage() { if (!state.results) return `${pageHead('Results', 'No evaluation yet', 'Run a patient evaluation to see ranked conditions and their supporting factors.', '<button class="pill" data-page="evaluate">Start evaluation</button>')}`; return `${pageHead('Results', 'Evaluation results', 'A transparent ranking of possible conditions based on the submitted information.', '<button class="pill" data-page="evaluate">New evaluation</button>')}<div class="notice" style="margin-bottom:20px">${escapeHtml(state.results.disclaimer)}</div><div class="results-list">${state.results.ranked_conditions.length ? state.results.ranked_conditions.map((condition, index) => resultCard(condition, index)).join('') : '<div class="panel empty">No ranked conditions matched the submitted information.</div>'}</div>`; }
function resultCard(item, index) { const percent = Math.round(item.likelihood_score * 100); const priority = item.priority_score >= .67 ? 'High' : item.priority_score >= .34 ? 'Moderate' : 'Low'; const detail = state.expanded === index ? `<div class="condition-detail"><div><h4>Matched symptoms</h4><ul class="detail-list">${factorList(item.matched_symptoms)}</ul></div><div><h4>Matched risk factors</h4><ul class="detail-list">${factorList(item.matched_risk_factors)}</ul></div><div><h4>Recommended tests</h4><ul class="detail-list">${item.recommended_tests.length ? item.recommended_tests.map(test => `<li>${escapeHtml(test.name)}</li>`).join('') : '<li>None stored</li>'}</ul><h4>Potential treatments</h4><ul class="detail-list">${item.treatments.length ? item.treatments.map(treatment => `<li>${escapeHtml(treatment.name)}</li>`).join('') : '<li>None stored</li>'}</ul></div><div class="explanation">${escapeHtml(item.explanation)}</div></div>` : ''; return `<article class="condition-card"><div class="condition-summary" data-expand="${index}"><div><h3>${escapeHtml(item.condition)}</h3><small>Based on stored clinical relationships</small></div><div class="metric"><span>Match score</span><strong>${percent}%</strong></div><div class="metric"><span>Severity</span><strong>${item.severity}/10</strong></div><div class="metric"><span>Urgency</span><strong>${item.urgency}/10</strong></div><span class="chevron">${state.expanded === index ? '−' : '+'}</span></div>${detail}</article>`; }
function factorList(factors) { return factors.length ? factors.map(factor => `<li>${escapeHtml(factor.name)} <small style="display:inline">(${factor.weight})</small></li>`).join('') : '<li>None matched</li>'; }
async function loadResource(type) { if (!type || state.data[type]) return; state.loading = true; render(); try { state.data[type] = await api(`/${type}`); } catch (error) { state.error = error.message; } finally { state.loading = false; render(); } }
function knowledgePage(type) { const config = resourceConfig[type]; const records = optionData(type); const query = state.kbQuery || ''; const filtered = records.filter(item => item.name.toLowerCase().includes(query.toLowerCase())); return `${pageHead('Knowledge base', config.label, 'Review the clinical resources available to the decision-support service.', `<button class="pill" data-add-resource="${type}">Add ${config.singular}</button>`)}<div class="kb-tabs">${Object.entries(resourceConfig).map(([key, value]) => `<button class="tab ${key === type ? 'active' : ''}" data-page="knowledge:${key}">${value.label}</button>`).join('')}</div><section class="panel"><div class="toolbar"><input id="kb-search" placeholder="Search ${config.label.toLowerCase()}..." value="${escapeHtml(query)}"></div>${state.error ? `<div class="error">${escapeHtml(state.error)}</div>` : ''}${state.loading ? '<div class="loading">Loading knowledge base...</div>' : filtered.length ? `<div class="table-wrap"><table><thead><tr><th>Name</th><th>Description</th><th>${type === 'risk-factors' ? 'Type' : type === 'tests' ? 'Purpose' : type === 'treatments' ? 'Type' : type === 'conditions' ? 'Severity / Urgency' : 'Record'}</th></tr></thead><tbody>${filtered.map(item => `<tr><td><strong>${escapeHtml(item.name)}</strong><small>#${item.id}</small></td><td>${escapeHtml(item.description || 'No description provided')}</td><td>${type === 'conditions' ? `${item.severity || '—'} / ${item.urgency || '—'}` : escapeHtml(item.type || '—')}</td></tr>`).join('')}</tbody></table></div>` : '<div class="empty">No resources found.</div>'}</section>`; }
function openResourceModal(type) { const config = resourceConfig[type]; const fields = config.fields.map(field => `<label>${field.replace('_', ' ')}${field === 'description' ? '<textarea name="description"></textarea>' : `<input name="${field}" ${field === 'severity' || field === 'urgency' ? 'type="number" min="1" max="10"' : ''} required>`}</label>`).join(''); document.body.insertAdjacentHTML('beforeend', `<div class="modal-backdrop" id="resource-modal"><form class="modal" id="resource-form"><header><h2>Add ${config.singular}</h2><button type="button" class="close" id="close-modal">x</button></header><div class="form-stack">${fields}</div><div class="form-actions"><button class="pill" type="submit">Create resource</button></div></form></div>`); document.querySelector('#close-modal').onclick = () => document.querySelector('#resource-modal').remove(); document.querySelector('#resource-form').onsubmit = async event => { event.preventDefault(); const payload = Object.fromEntries(new FormData(event.currentTarget)); if (payload.severity) payload.severity = Number(payload.severity); if (payload.urgency) payload.urgency = Number(payload.urgency); try { await api(`/${type}`, { method: 'POST', body: JSON.stringify(payload) }); document.querySelector('#resource-modal').remove(); delete state.data[type]; await loadResource(type); toast(`${config.label.slice(0, -1)} created`); } catch (error) { toast(error.message); } }; }
function toast(message) { document.body.insertAdjacentHTML('beforeend', `<div class="toast">${escapeHtml(message)}</div>`); setTimeout(() => document.querySelector('.toast')?.remove(), 3200); }
function bindEvents() { document.querySelectorAll('[data-page]').forEach(element => element.onclick = event => { event.preventDefault(); const page = element.dataset.page; if (page === 'home') { state.page = 'home'; render(); } else go(page); }); const menu = document.querySelector('#menu-button'); if (menu) menu.onclick = () => document.querySelector('#sidebar').classList.toggle('open'); document.querySelector('#evaluation-form')?.addEventListener('submit', event => { event.preventDefault(); submitEvaluation(event.currentTarget); }); document.querySelectorAll('[data-add]').forEach(element => element.onclick = () => { const key = element.dataset.add === 'symptoms' ? 'selectedSymptoms' : 'selectedRisks'; if (!state[key].includes(element.dataset.value)) state[key].push(element.dataset.value); render(); }); document.querySelectorAll('[data-remove]').forEach(element => element.onclick = () => { const key = element.dataset.remove === 'symptoms' ? 'selectedSymptoms' : 'selectedRisks'; state[key] = state[key].filter(value => value !== element.dataset.value); render(); }); document.querySelectorAll('[data-search]').forEach(element => element.oninput = event => { const key = event.target.dataset.search === 'symptoms' ? 'symptomsQuery' : 'risksQuery'; state[key] = event.target.value; render(); document.querySelector(`[data-search="${event.target.dataset.search}"]`)?.focus(); }); document.querySelectorAll('[data-expand]').forEach(element => element.onclick = () => { state.expanded = Number(element.dataset.expand) === state.expanded ? -1 : Number(element.dataset.expand); render(); }); document.querySelector('#kb-search')?.addEventListener('input', event => { state.kbQuery = event.target.value; render(); document.querySelector('#kb-search')?.focus(); }); document.querySelector('[data-add-resource]')?.addEventListener('click', event => openResourceModal(event.currentTarget.dataset.addResource)); }
render();
